import { useState } from "react";
import { useLanguage } from "@/contexts/LanguageContext";
import AppLayout from "@/components/AppLayout";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import {
  Megaphone,
  Plus,
  Zap,
  Mail,
  MessageSquare,
  Phone,
  Layers,
  Play,
  Pause,
  CheckCircle2,
  Clock,
  XCircle,
  Bot,
  Copy,
  BarChart2,
  Target,
  Filter,
} from "lucide-react";

const CHANNEL_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  email: Mail,
  whatsapp: MessageSquare,
  sms: Phone,
  multi: Layers,
};

const STATUS_CONFIG: Record<string, { color: string; icon: React.ComponentType<{ className?: string }> }> = {
  draft: { color: "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400", icon: Clock },
  pending_approval: { color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-950 dark:text-yellow-300", icon: Clock },
  active: { color: "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-300", icon: Play },
  paused: { color: "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300", icon: Pause },
  completed: { color: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300", icon: CheckCircle2 },
  cancelled: { color: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300", icon: XCircle },
};

function AIContentGenerator({ onGenerated }: { onGenerated: (data: { subject: string; message: string; cta: string }) => void }) {
  const { t, language } = useLanguage();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ objective: "leads", channel: "email", niche: "services", brandVoice: "friendly" });

  const generateContent = trpc.campaigns.generateContent.useMutation({
    onSuccess: (data) => {
      onGenerated(data);
      setOpen(false);
      toast.success("Content generated by AI!");
    },
    onError: (e) => toast.error(e.message),
  });

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2 border-primary text-primary hover:bg-primary/5">
          <Bot className="w-4 h-4" />
          {t("ai.central")} — Generate Content
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="w-5 h-5 text-primary" />
            AI Content Generator
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-3 mt-2">
          <div className="space-y-1">
            <Label>Objective</Label>
            <Select value={form.objective} onValueChange={(v) => setForm((f) => ({ ...f, objective: v }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["leads", "sales", "booking", "retention", "followup", "reactivation"].map((o) => (
                  <SelectItem key={o} value={o}>{t(`campaigns.objectives.${o}`)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1">
            <Label>Channel</Label>
            <Select value={form.channel} onValueChange={(v) => setForm((f) => ({ ...f, channel: v }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["email", "whatsapp", "sms"].map((c) => (
                  <SelectItem key={c} value={c}>{c.charAt(0).toUpperCase() + c.slice(1)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1">
            <Label>Business Niche</Label>
            <Select value={form.niche} onValueChange={(v) => setForm((f) => ({ ...f, niche: v }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["services", "health", "beauty", "realestate", "insurance", "legal", "accounting"].map((n) => (
                  <SelectItem key={n} value={n}>{t(`onboarding.businessTypes.${n}`)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1">
            <Label>Brand Voice</Label>
            <Select value={form.brandVoice} onValueChange={(v) => setForm((f) => ({ ...f, brandVoice: v }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["professional", "friendly", "energetic", "empathetic", "authoritative"].map((v) => (
                  <SelectItem key={v} value={v}>{t(`onboarding.brandVoice.${v}`)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="flex justify-end gap-2 mt-4">
          <Button variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
          <Button
            className="brand-gradient text-white border-0 gap-2"
            disabled={generateContent.isPending}
            onClick={() => generateContent.mutate({ ...form, language })}
          >
            {generateContent.isPending ? (
              <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
            ) : (
              <><Zap className="w-4 h-4" /> Generate</>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function CreateCampaignDialog({ onSuccess }: { onSuccess: () => void }) {
  const { t, language } = useLanguage();
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(1);
  type CampaignChannel = "email" | "whatsapp" | "sms" | "multi";
  type CampaignObjective = "leads" | "sales" | "booking" | "retention" | "followup" | "reactivation";
  const [form, setForm] = useState<{
    name: string;
    objective: CampaignObjective;
    channel: CampaignChannel;
    language: string;
    targetNiche: string;
    generatedContent: { subject: string; message: string; cta: string } | null;
  }>({
    name: "",
    objective: "leads",
    channel: "email",
    language: language,
    targetNiche: "services",
    generatedContent: null,
  });

  const createCampaign = trpc.campaigns.create.useMutation({
    onSuccess: () => {
      toast.success("Campaign created!");
      setOpen(false);
      setStep(1);
      onSuccess();
    },
    onError: (e) => toast.error(e.message),
  });

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="brand-gradient text-white border-0 gap-2">
          <Plus className="w-4 h-4" />
          {t("campaigns.create")}
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>{t("campaigns.create")}</DialogTitle>
        </DialogHeader>

        {step === 1 && (
          <div className="space-y-4 mt-2">
            <div className="space-y-1">
              <Label>Campaign Name *</Label>
              <Input
                value={form.name}
                onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                placeholder="e.g. Summer Promo 2025"
              />
            </div>
            <div className="space-y-1">
              <Label>Objective</Label>
              <div className="grid grid-cols-2 gap-2">
                {(["leads", "sales", "booking", "retention", "followup", "reactivation"] as const).map((obj) => (
                  <button
                    key={obj}
                    onClick={() => setForm((f) => ({ ...f, objective: obj }))}
                    className={cn(
                      "p-3 rounded-lg border-2 text-sm text-left transition-all",
                      form.objective === obj ? "border-primary bg-primary/5 font-semibold" : "border-border hover:border-primary/40"
                    )}
                  >
                    {t(`campaigns.objectives.${obj}`)}
                  </button>
                ))}
              </div>
            </div>
            <div className="space-y-1">
              <Label>Channel</Label>
              <div className="grid grid-cols-4 gap-2">
                {(["email", "whatsapp", "sms", "multi"] as const).map((ch) => {
                  const Icon = CHANNEL_ICONS[ch];
                  return (
                    <button
                      key={ch}
                      onClick={() => setForm((f) => ({ ...f, channel: ch }))}
                      className={cn(
                        "flex flex-col items-center gap-1.5 p-3 rounded-lg border-2 text-xs transition-all",
                        form.channel === ch ? "border-primary bg-primary/5 font-semibold" : "border-border hover:border-primary/40"
                      )}
                    >
                      <Icon className="w-5 h-5" />
                      {ch.charAt(0).toUpperCase() + ch.slice(1)}
                    </button>
                  );
                })}
              </div>
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
              <Button
                className="brand-gradient text-white border-0"
                disabled={!form.name}
                onClick={() => setStep(2)}
              >
                {t("common.next")}
              </Button>
            </div>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-4 mt-2">
            <div className="p-4 bg-muted/50 rounded-xl space-y-3">
              <p className="text-sm font-medium flex items-center gap-2">
                <Bot className="w-4 h-4 text-primary" />
                AI-Generated Content
              </p>
              {form.generatedContent ? (
                <div className="space-y-2">
                  <div>
                    <p className="text-xs text-muted-foreground">Subject</p>
                    <p className="text-sm font-medium">{form.generatedContent.subject}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Message</p>
                    <p className="text-sm">{form.generatedContent.message}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">CTA</p>
                    <p className="text-sm font-semibold text-primary">{form.generatedContent.cta}</p>
                  </div>
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">Use AI to generate campaign content, or write your own below.</p>
              )}
              <AIContentGenerator onGenerated={(data) => setForm((f) => ({ ...f, generatedContent: data }))} />
            </div>
            <div className="flex justify-between gap-2">
              <Button variant="outline" onClick={() => setStep(1)}>{t("common.back")}</Button>
              <Button
                className="brand-gradient text-white border-0"
                disabled={createCampaign.isPending}
                onClick={() => createCampaign.mutate({
                  name: form.name,
                  objective: form.objective,
                  channel: form.channel,
                  language: form.language,
                  targetNiche: form.targetNiche,
                })}
              >
                {createCampaign.isPending ? t("common.loading") : t("common.save")}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

export default function Campaigns() {
  const { t } = useLanguage();
  const [statusFilter, setStatusFilter] = useState("all");
  const [channelFilter, setChannelFilter] = useState("all");

  const { data: campaigns = [], refetch } = trpc.campaigns.list.useQuery({
    status: statusFilter !== "all" ? statusFilter : undefined,
    channel: channelFilter !== "all" ? channelFilter : undefined,
  });

  const updateStatus = trpc.campaigns.updateStatus.useMutation({
    onSuccess: () => { toast.success("Status updated!"); refetch(); },
    onError: (e) => toast.error(e.message),
  });

  const stats = [
    { label: "Total Campaigns", value: (campaigns as Record<string, unknown>[]).length, icon: Megaphone, color: "text-primary" },
    { label: "Active", value: (campaigns as Record<string, unknown>[]).filter((c) => c.status === "active").length, icon: Play, color: "text-green-500" },
    { label: "Pending Approval", value: (campaigns as Record<string, unknown>[]).filter((c) => c.status === "pending_approval").length, icon: Clock, color: "text-yellow-500" },
    { label: "Completed", value: (campaigns as Record<string, unknown>[]).filter((c) => c.status === "completed").length, icon: CheckCircle2, color: "text-blue-500" },
  ];

  return (
    <AppLayout>
      <div className="p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">{t("campaigns.title")}</h1>
            <p className="text-muted-foreground text-sm mt-1">
              Create and manage email, WhatsApp and SMS campaigns
            </p>
          </div>
          <CreateCampaignDialog onSuccess={refetch} />
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {stats.map((stat) => {
            const Icon = stat.icon;
            return (
              <Card key={stat.label} className="border-border">
                <CardContent className="p-4 flex items-center gap-3">
                  <div className={cn("w-10 h-10 rounded-lg bg-muted flex items-center justify-center", stat.color)}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold">{stat.value}</p>
                    <p className="text-xs text-muted-foreground">{stat.label}</p>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Filters */}
        <div className="flex gap-3 flex-wrap">
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-44">
              <Filter className="w-4 h-4 mr-2" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              {["draft", "pending_approval", "active", "paused", "completed", "cancelled"].map((s) => (
                <SelectItem key={s} value={s}>{t(`campaigns.status.${s}`)}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={channelFilter} onValueChange={setChannelFilter}>
            <SelectTrigger className="w-36">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Channels</SelectItem>
              {["email", "whatsapp", "sms", "multi"].map((c) => (
                <SelectItem key={c} value={c}>{c.charAt(0).toUpperCase() + c.slice(1)}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Campaigns list */}
        {(campaigns as Record<string, unknown>[]).length === 0 ? (
          <div className="text-center py-16 space-y-4">
            <Megaphone className="w-12 h-12 text-muted-foreground/30 mx-auto" />
            <p className="text-muted-foreground">{t("common.noData")}</p>
            <CreateCampaignDialog onSuccess={refetch} />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            {(campaigns as Record<string, unknown>[]).map((campaign) => {
              const status = String(campaign.status ?? "draft");
              const channel = String(campaign.channel ?? "email");
              const statusConf = STATUS_CONFIG[status] ?? STATUS_CONFIG.draft;
              const StatusIcon = statusConf.icon;
              const ChannelIcon = CHANNEL_ICONS[channel] ?? Mail;
              const stats = campaign.stats as { sent: number; opened: number; clicked: number; converted: number } | null;

              return (
                <Card key={String(campaign.id)} className="border-border hover:shadow-md transition-all">
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-2 min-w-0">
                        <div className="w-8 h-8 rounded-lg brand-gradient flex items-center justify-center flex-shrink-0">
                          <ChannelIcon className="w-4 h-4 text-white" />
                        </div>
                        <CardTitle className="text-sm truncate">{String(campaign.name ?? "")}</CardTitle>
                      </div>
                      <Badge className={cn("text-[10px] px-2 py-0.5 flex items-center gap-1 flex-shrink-0", statusConf.color)}>
                        <StatusIcon className="w-3 h-3" />
                        {t(`campaigns.status.${status}`)}
                      </Badge>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <Target className="w-3.5 h-3.5" />
                      <span>{t(`campaigns.objectives.${String(campaign.objective ?? "leads")}`)}</span>
                    </div>

                    {stats && (stats.sent > 0) && (
                      <div className="grid grid-cols-4 gap-2 p-2 bg-muted/50 rounded-lg">
                        {[
                          { label: "Sent", value: stats.sent },
                          { label: "Opened", value: stats.opened },
                          { label: "Clicked", value: stats.clicked },
                          { label: "Converted", value: stats.converted },
                        ].map(({ label, value }) => (
                          <div key={label} className="text-center">
                            <p className="text-sm font-bold">{value}</p>
                            <p className="text-[10px] text-muted-foreground">{label}</p>
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="flex gap-2">
                      {status === "draft" && (
                        <Button
                          size="sm"
                          className="flex-1 h-7 text-xs brand-gradient text-white border-0"
                          onClick={() => updateStatus.mutate({ id: Number(campaign.id), status: "active" })}
                        >
                          <Play className="w-3 h-3 mr-1" /> Activate
                        </Button>
                      )}
                      {status === "active" && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="flex-1 h-7 text-xs"
                          onClick={() => updateStatus.mutate({ id: Number(campaign.id), status: "paused" })}
                        >
                          <Pause className="w-3 h-3 mr-1" /> Pause
                        </Button>
                      )}
                      {status === "paused" && (
                        <Button
                          size="sm"
                          className="flex-1 h-7 text-xs brand-gradient text-white border-0"
                          onClick={() => updateStatus.mutate({ id: Number(campaign.id), status: "active" })}
                        >
                          <Play className="w-3 h-3 mr-1" /> Resume
                        </Button>
                      )}
                      <Button size="sm" variant="ghost" className="h-7 w-7 p-0">
                        <BarChart2 className="w-3.5 h-3.5" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </AppLayout>
  );
}
