import { useState } from "react";
import { useLanguage } from "@/contexts/LanguageContext";
import AppLayout from "@/components/AppLayout";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import {
  Share2,
  Plus,
  Bot,
  Calendar,
  Clock,
  CheckCircle2,
  XCircle,
  Image,
  Hash,
  TrendingUp,
  Eye,
  Heart,
  MessageSquare,
  Repeat2,
  Zap,
  Instagram,
  Linkedin,
  Facebook,
  Twitter,
} from "lucide-react";

const CHANNEL_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  instagram: Instagram,
  linkedin: Linkedin,
  facebook: Facebook,
  twitter: Twitter,
};

const STATUS_CONFIG: Record<string, { color: string; label: string }> = {
  draft: { color: "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400", label: "Draft" },
  scheduled: { color: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300", label: "Scheduled" },
  published: { color: "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-300", label: "Published" },
  failed: { color: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300", label: "Failed" },
};

function AIPostGenerator({ onGenerated }: { onGenerated: (data: { content: string; hashtags: string[] }) => void }) {
  const { t, language } = useLanguage();
  const [open, setOpen] = useState(false);
  type PostAudience = "b2b" | "b2c" | "both";
  type PostType = "organic" | "ad" | "story" | "reel";
  const [form, setForm] = useState<{ topic: string; niche: string; audience: PostAudience; postType: PostType }>({
    topic: "",
    niche: "services",
    audience: "both",
    postType: "organic",
  });

  const generatePost = trpc.social.generatePost.useMutation({
    onSuccess: (data) => {
      onGenerated(data);
      setOpen(false);
      toast.success("Post generated by AI!");
    },
    onError: (e) => toast.error(e.message),
  });

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2 border-primary text-primary hover:bg-primary/5">
          <Bot className="w-4 h-4" />
          AI Generate Post
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="w-5 h-5 text-primary" />
            AI Post Generator
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-3 mt-2">
          <div className="space-y-1">
            <Label>Topic / Theme *</Label>
            <Input
              value={form.topic}
              onChange={(e) => setForm((f) => ({ ...f, topic: e.target.value }))}
              placeholder="e.g. New product launch, tips, promotion..."
            />
          </div>
          <div className="space-y-1">
            <Label>Business Niche</Label>
            <Select value={form.niche} onValueChange={(v) => setForm((f) => ({ ...f, niche: v }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["services", "health", "beauty", "realestate", "insurance", "legal", "accounting", "retail", "tech"].map((n) => (
                  <SelectItem key={n} value={n}>{t(`onboarding.businessTypes.${n}`)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1">
            <Label>Target Audience</Label>
            <Select value={form.audience} onValueChange={(v) => setForm((f) => ({ ...f, audience: v as "b2b" | "b2c" | "both" }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="b2b">B2B (Business)</SelectItem>
                <SelectItem value="b2c">B2C (Consumer)</SelectItem>
                <SelectItem value="both">Both</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="flex justify-end gap-2 mt-4">
          <Button variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
          <Button
            className="brand-gradient text-white border-0 gap-2"
            disabled={!form.topic || generatePost.isPending}
            onClick={() => generatePost.mutate({ ...form, language })}
          >
            {generatePost.isPending ? (
              <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
            ) : (
              <><Zap className="w-4 h-4" /> Generate</>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function CreatePostDialog({ onSuccess }: { onSuccess: () => void }) {
  const { t, language } = useLanguage();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({
    content: "",
    hashtags: [] as string[],
    channels: [] as string[],
    postType: "organic" as const,
    audience: "both" as const,
    language: language,
    scheduledAt: "",
  });
  const [hashtagInput, setHashtagInput] = useState("");

  const createPost = trpc.social.createPost.useMutation({
    onSuccess: () => {
      toast.success("Post created!");
      setOpen(false);
      onSuccess();
    },
    onError: (e) => toast.error(e.message),
  });

  const addHashtag = () => {
    const tag = hashtagInput.trim().replace(/^#/, "");
    if (tag && !form.hashtags.includes(tag)) {
      setForm((f) => ({ ...f, hashtags: [...f.hashtags, tag] }));
      setHashtagInput("");
    }
  };

  const toggleChannel = (ch: string) => {
    setForm((f) => ({
      ...f,
      channels: f.channels.includes(ch) ? f.channels.filter((c) => c !== ch) : [...f.channels, ch],
    }));
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="brand-gradient text-white border-0 gap-2">
          <Plus className="w-4 h-4" />
          {t("social.createPost")}
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{t("social.createPost")}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 mt-2">
          <AIPostGenerator onGenerated={(data) => setForm((f) => ({ ...f, content: data.content, hashtags: data.hashtags }))} />

          <div className="space-y-1">
            <Label>Post Content *</Label>
            <Textarea
              value={form.content}
              onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))}
              rows={5}
              placeholder="Write your post content here..."
            />
            <p className="text-xs text-muted-foreground text-right">{form.content.length} chars</p>
          </div>

          <div className="space-y-2">
            <Label>Channels</Label>
            <div className="flex gap-2 flex-wrap">
              {["instagram", "facebook", "linkedin", "twitter"].map((ch) => {
                const Icon = CHANNEL_ICONS[ch];
                return (
                  <button
                    key={ch}
                    onClick={() => toggleChannel(ch)}
                    className={cn(
                      "flex items-center gap-1.5 px-3 py-1.5 rounded-full border-2 text-xs transition-all",
                      form.channels.includes(ch) ? "border-primary bg-primary/5 font-semibold" : "border-border hover:border-primary/40"
                    )}
                  >
                    <Icon className="w-3.5 h-3.5" />
                    {ch.charAt(0).toUpperCase() + ch.slice(1)}
                  </button>
                );
              })}
            </div>
          </div>

          <div className="space-y-2">
            <Label>Hashtags</Label>
            <div className="flex gap-2">
              <Input
                value={hashtagInput}
                onChange={(e) => setHashtagInput(e.target.value)}
                placeholder="#hashtag"
                onKeyDown={(e) => e.key === "Enter" && addHashtag()}
              />
              <Button variant="outline" size="sm" onClick={addHashtag}>Add</Button>
            </div>
            {form.hashtags.length > 0 && (
              <div className="flex flex-wrap gap-1">
                {form.hashtags.map((tag) => (
                  <Badge
                    key={tag}
                    variant="secondary"
                    className="cursor-pointer hover:bg-destructive/10 hover:text-destructive"
                    onClick={() => setForm((f) => ({ ...f, hashtags: f.hashtags.filter((h) => h !== tag) }))}
                  >
                    #{tag} ×
                  </Badge>
                ))}
              </div>
            )}
          </div>

          <div className="space-y-1">
            <Label>Schedule (optional)</Label>
            <Input
              type="datetime-local"
              value={form.scheduledAt}
              onChange={(e) => setForm((f) => ({ ...f, scheduledAt: e.target.value }))}
            />
          </div>
        </div>
        <div className="flex justify-end gap-2 mt-4">
          <Button variant="outline" onClick={() => setOpen(false)}>{t("common.cancel")}</Button>
          <Button
            className="brand-gradient text-white border-0"
            disabled={!form.content || createPost.isPending}
            onClick={() => createPost.mutate({
              content: form.content,
              hashtags: form.hashtags,
              channels: form.channels,
              postType: form.postType,
              audience: form.audience,
              language: form.language,
              scheduledAt: form.scheduledAt ? new Date(form.scheduledAt) : undefined,
            })}
          >
            {createPost.isPending ? t("common.loading") : t("common.save")}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function PostCard({ post }: { post: Record<string, unknown> }) {
  const status = String(post.status ?? "draft");
  const statusConf = STATUS_CONFIG[status] ?? STATUS_CONFIG.draft;
  const hashtags = (post.hashtags as string[]) ?? [];
  const channels = (post.channels as string[]) ?? [];
  const stats = post.stats as { likes: number; comments: number; shares: number; reach: number; clicks: number } | null;

  return (
    <Card className="border-border hover:shadow-md transition-all">
      <CardContent className="p-4 space-y-3">
        <div className="flex items-start justify-between gap-2">
          <div className="flex gap-1.5 flex-wrap">
            {channels.map((ch) => {
              const Icon = CHANNEL_ICONS[ch];
              return Icon ? (
                <div key={ch} className="w-6 h-6 rounded-full bg-muted flex items-center justify-center">
                  <Icon className="w-3.5 h-3.5 text-muted-foreground" />
                </div>
              ) : null;
            })}
          </div>
          <Badge className={cn("text-[10px] px-2 py-0.5 flex-shrink-0", statusConf.color)}>
            {statusConf.label}
          </Badge>
        </div>

        <p className="text-sm line-clamp-3 text-foreground">{String(post.content ?? "")}</p>

        {hashtags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {hashtags.slice(0, 4).map((tag) => (
              <span key={tag} className="text-[10px] text-primary font-medium">#{tag}</span>
            ))}
            {hashtags.length > 4 && <span className="text-[10px] text-muted-foreground">+{hashtags.length - 4}</span>}
          </div>
        )}

        {Boolean(post.scheduledAt) && (
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Clock className="w-3.5 h-3.5" />
            {new Date(String(post.scheduledAt)).toLocaleString()}
          </div>
        )}

        {stats && stats.reach > 0 && (
          <div className="grid grid-cols-4 gap-1 p-2 bg-muted/50 rounded-lg">
            {[
              { icon: Eye, value: stats.reach, label: "Reach" },
              { icon: Heart, value: stats.likes, label: "Likes" },
              { icon: MessageSquare, value: stats.comments, label: "Comments" },
              { icon: Repeat2, value: stats.shares, label: "Shares" },
            ].map(({ icon: Icon, value, label }) => (
              <div key={label} className="text-center">
                <p className="text-xs font-bold">{value}</p>
                <p className="text-[9px] text-muted-foreground">{label}</p>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export default function SocialMedia() {
  const { t } = useLanguage();
  const [statusFilter, setStatusFilter] = useState("all");
  const [activeTab, setActiveTab] = useState("posts");

  const { data: posts = [], refetch } = trpc.social.listPosts.useQuery({
    status: statusFilter !== "all" ? statusFilter : undefined,
  });

  const stats = [
    { label: "Total Posts", value: (posts as Record<string, unknown>[]).length, icon: Share2, color: "text-primary" },
    { label: "Scheduled", value: (posts as Record<string, unknown>[]).filter((p) => p.status === "scheduled").length, icon: Calendar, color: "text-blue-500" },
    { label: "Published", value: (posts as Record<string, unknown>[]).filter((p) => p.status === "published").length, icon: CheckCircle2, color: "text-green-500" },
    { label: "Drafts", value: (posts as Record<string, unknown>[]).filter((p) => p.status === "draft").length, icon: Clock, color: "text-gray-500" },
  ];

  return (
    <AppLayout>
      <div className="p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">{t("social.title")}</h1>
            <p className="text-muted-foreground text-sm mt-1">
              Plan, create and schedule your social media content
            </p>
          </div>
          <CreatePostDialog onSuccess={refetch} />
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {stats.map((stat) => {
            const Icon = stat.icon;
            return (
              <Card key={stat.label} className="border-border">
                <CardContent className="p-4 flex items-center gap-3">
                  <div className={cn("w-10 h-10 rounded-lg bg-muted flex items-center justify-center", stat.color)}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold">{stat.value}</p>
                    <p className="text-xs text-muted-foreground">{stat.label}</p>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <div className="flex items-center justify-between">
            <TabsList>
              <TabsTrigger value="posts">All Posts</TabsTrigger>
              <TabsTrigger value="calendar">Calendar</TabsTrigger>
              <TabsTrigger value="analytics">Analytics</TabsTrigger>
            </TabsList>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-36">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                {["draft", "scheduled", "published", "failed"].map((s) => (
                  <SelectItem key={s} value={s}>{STATUS_CONFIG[s]?.label ?? s}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <TabsContent value="posts" className="mt-4">
            {(posts as Record<string, unknown>[]).length === 0 ? (
              <div className="text-center py-16 space-y-4">
                <Share2 className="w-12 h-12 text-muted-foreground/30 mx-auto" />
                <p className="text-muted-foreground">{t("common.noData")}</p>
                <CreatePostDialog onSuccess={refetch} />
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {(posts as Record<string, unknown>[]).map((post) => (
                  <PostCard key={String(post.id)} post={post} />
                ))}
              </div>
            )}
          </TabsContent>

          <TabsContent value="calendar" className="mt-4">
            <div className="bg-card border border-border rounded-xl p-6 text-center">
              <Calendar className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-muted-foreground">Visual calendar view — coming soon</p>
              <p className="text-sm text-muted-foreground mt-1">Schedule and visualize your content calendar</p>
            </div>
          </TabsContent>

          <TabsContent value="analytics" className="mt-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Card className="border-border">
                <CardHeader>
                  <CardTitle className="text-sm flex items-center gap-2">
                    <TrendingUp className="w-4 h-4 text-primary" />
                    Performance Overview
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {[
                      { label: "Total Reach", value: (posts as Record<string, unknown>[]).reduce((s, p) => s + ((p.stats as Record<string, number> | null)?.reach ?? 0), 0) },
                      { label: "Total Likes", value: (posts as Record<string, unknown>[]).reduce((s, p) => s + ((p.stats as Record<string, number> | null)?.likes ?? 0), 0) },
                      { label: "Total Comments", value: (posts as Record<string, unknown>[]).reduce((s, p) => s + ((p.stats as Record<string, number> | null)?.comments ?? 0), 0) },
                      { label: "Total Shares", value: (posts as Record<string, unknown>[]).reduce((s, p) => s + ((p.stats as Record<string, number> | null)?.shares ?? 0), 0) },
                    ].map(({ label, value }) => (
                      <div key={label} className="flex items-center justify-between">
                        <span className="text-sm text-muted-foreground">{label}</span>
                        <span className="font-bold">{value.toLocaleString()}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
              <Card className="border-border">
                <CardHeader>
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Hash className="w-4 h-4 text-primary" />
                    Top Hashtags
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {Array.from(
                      new Set((posts as Record<string, unknown>[]).flatMap((p) => (p.hashtags as string[]) ?? []))
                    ).slice(0, 12).map((tag) => (
                      <Badge key={tag} variant="secondary" className="text-xs">#{tag}</Badge>
                    ))}
                    {(posts as Record<string, unknown>[]).length === 0 && (
                      <p className="text-sm text-muted-foreground">No hashtags yet</p>
                    )}
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </AppLayout>
  );
}
